spring:

  application:
    name: Brief15-Bibliotheque

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_brief15
    username: postgres
    password: postgres

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework: DEBUG

server:
  servlet:
    context-path: /api