create table emprunteur
(
    id     bigint generated by default as identity
        primary key,
    email  varchar(255) not null
        unique,
    nom    varchar(255) not null,
    prenom varchar(255) not null
);

create table genre
(
    id      bigint generated by default as identity
        primary key,
    libelle varchar(255)
);

create table livre
(
    disponibilite boolean      not null,
    id            bigint generated by default as identity
        primary key,
    auteur        varchar(255) not null,
    titre         varchar(255) not null
);

create table emprunt
(
    date_emprunt  timestamp(6),
    date_retour   timestamp(6),
    emprunteur_id bigint
        constraint fkopcrsgar1t252ct8t0pca7vug
            references emprunteur,
    id            bigint generated by default as identity
        primary key,
    livre_id      bigint
        constraint fkjnn7ll8vl64xhmb6779svt7c
            references livre
);

create table livre_genre
(
    genre_id bigint not null
        constraint fk5rigktent3gmqmv269xen042s
            references genre,
    livre_id bigint not null
        constraint fk2e3wcedft29f0p74sg1kxij3i
            references livre
);

